SECKEY='c0)-tq#*0eayb8*z^t10p(#sp6=d*j%$x%5-l-=+s(lmuypm51'
DBNAME=''
DBSVER=''
DBUSER=''
DBPASS=''
DEBUG=True
ALLHOS=[]
ULCONF='Snarl.urls'
WSGAPP='Snarl.wsgi.application'
LNCODE='en-us'
TMZONE='UTC'
USIIBN=True
USLION=True
USETZI=True
STAURL='/static/'
DBASES={'default': {'ENGINE': 'django.db.backends.sqlite3', 'NAME': ''}}
INAPPS=['dashboard.apps.DashboardConfig', 'jet', 'django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles']
MDWARE=['django.middleware.security.SecurityMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware']
TEMPLS=[{'BACKEND': 'django.template.backends.django.DjangoTemplates', 'DIRS': [], 'APP_DIRS': True, 'OPTIONS': {'context_processors': ['django.template.context_processors.debug', 'django.template.context_processors.request', 'django.contrib.auth.context_processors.auth', 'django.contrib.messages.context_processors.messages']}}]
AUVALI=[{'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'}, {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'}, {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'}, {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'}]
JDEFTH='light-gray'
STADIR=[]
